//
// boot.c
//
// DO NOT EDIT THIS FILE.  This file was generated automatically
// by a script that converts an assembler listing into a C structure
// containing the hex values of the instructions in the listing.
// You must edit the assembler source directly and execute the build
// again.
// mipsel-linux-gcc -mips32 -Wa,-al -EL -c boot.S |perl -ane 'if(/([\dA-F]{8})\s+(.*)/){$a=unpack(q(I),pack(q(H*),$1));printf qq(0x%08X, //%s\n),$a,$2;} elsif(/\d+\s+(.+)/){print qq(         //$1\n);}'
//

static unsigned int aui_boot_code[] = {
         //# 1 "boot.S"
         //.text
         //
         //
         //.global _start;
         //_start:
0x3C02BF08, //li $v0, 0xbf088008
0x34428008, //
         //1:
0x8C430000, //lw $v1,($v0)
0x1460FFFE, //bnez $v1, 1b
0x00000000, //
0x00000000, //nop
0x3C028020, //li $v0,0x8020d200
0x3442D200, //
0x00400008, //jr $v0
0x00000000, //
0x00000000, //nop
0x00000000, //
};


